# Generated by Django 4.1.6 on 2023-02-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_alter_state_description_alter_state_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('child_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_id', to='sampling.state')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.state')),
            ],
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
