# Generated by Django 4.1.6 on 2023-02-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0003_option_delete_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='options',
        ),
    ]
