# Generated by Django 4.1.6 on 2023-02-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0004_rename_option_option_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='options',
            new_name='option',
        ),
    ]
