# Generated by Django 4.1.6 on 2023-02-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0005_rename_options_option_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='state',
            name='description',
        ),
        migrations.RemoveField(
            model_name='state',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='state',
            name='parent_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.state'),
        ),
        migrations.AddField(
            model_name='state',
            name='term',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
