# Generated by Django 4.1.6 on 2023-02-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0006_rename_option_option_name_remove_state_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='child_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_state', to='sampling.state'),
        ),
    ]
