# Generated by Django 4.1.6 on 2023-02-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0008_alter_state_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='child_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_state', to='sampling.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='parent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampling.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='term',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
